config/routes.rb
Rails.application.routes.draw do
  root 'sessions#splashpage'
  # root 'sessions#new' #TODO work on this one!

  resources :sessions
  resources :users
  resources :loans

  # get '/cool' => 'rails#cool'
  # get '/sweet' => 'rails#sweet'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  #
  # post '/login' => 'sessions#create'
  # get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#create'
  get '/profilepage' => 'sessions#profilepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	# has_many :borrowings, class_name: "Loan", foreign_key: "borrower_id"
	# has_many :lendings, class_name: "Loan", foreign_key: "lender_id"

  has_secure_password
  enum role: [:Lender, :Borrower, :Admin]
  has_many :loans
  # has_many :users, :source => :lender, :through => :loans
  # has_many :borrowers, class_name: "User", foreign_key: "lender_id"
  # belongs_to :lender, class_name: "User"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :check_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if current_user == @user
      @lender_loans = Loan.where(lender_id: @user)
      @p_count = 0 #count of pending loans
      @a_count = 0 #count of active loans
      @c_count = 0 #count of completed loans

      @lender_loans.each do |pending|
        if pending.status == "Pending"
          @p_count = @p_count + 1
        end
      end

      @lender_loans.each do |active|
        if active.status == "Active"
          @a_count = @a_count + 1
        end
      end

      @lender_loans.each do |completed|
        if completed.status == "Completed"
          @c_count = @c_count + 1
        end
      end
    else
      redirect_to profile_path(current_user)
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    return render action: 'new' unless @user.save

    client = Dwolla.new

    first_name = @user.first_name
    last_name = @user.last_name
    email = @user.email
    type = "personal"
    address = @user.address
    city = @user.city
    state = @user.state
    postal_code = @user.postal_code
    date_of_birth = @user.date_of_birth
    last_four_of_ssn = @user.last_four_of_ssn

    client.create_customer(first_name, last_name, email, type, address, city, state, postal_code, date_of_birth, last_four_of_ssn)
    redirect_to user_path(@user), notice: 'Created user'
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # def check_user
    #   if current_user.id != @user
    #     redirect_to root_path
    #   end
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :role, :username, :password, :password_confirmation, :address, :city, :state, :postal_code, :date_of_birth, :last_four_of_ssn)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title alert alert-info">Sign up to continue to $iou</h1>
            <div class="wall">
                <img id="logo" src="https://trello-attachments.s3.amazonaws.com/5a00dc322b3c3a3c721a6912/5a00e674cdb313f96d9cdb2c/539b280fb58aee03ce2fe36c62fdae39/Logaster-13-vk-sharedImage-1000px.png"
                    alt="">
                <%= form_with(model: user, local: true, class: "all-form") do |form| %>
                    <% if user.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                        <ul>
                        <% user.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="field">
                      <%= form.label :first_name %>
                      <%= form.text_field :first_name, id: :user_first_name, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :last_name %>
                      <%= form.text_field :last_name, id: :user_last_name, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :username %>
                      <%= form.text_field :username, id: :user_username, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :email %>
                      <%= form.text_field :email, id: :user_email, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :address %>
                      <%= form.text_field :address, id: :user_address, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :city %>
                      <%= form.text_field :city, id: :user_city, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :state %>
                      <%= form.text_field :state, id: :user_state, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :postal_code %>
                      <%= form.text_field :postal_code, id: :user_postal_code, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :date_of_birth %> (YYYY-MM-DD)
                      <%= form.text_field :date_of_birth, id: :user_date_of_birth, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :last_four_of_ssn %>
                      <%= form.text_field :last_four_of_ssn, id: :user_last_four_of_ssn, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :role %>
                      <%= form.select :role, ['','Lender', 'Borrower'], class: "form-control" %>

                    </div>

                    <div class="field">
                      <%= form.label :password %>
                      <%= form.password_field :password, id: :user_password, class: "form-control" %>
                    </div>

                    <div class="field">
                      <%= form.label :password_confirmation %>
                      <%= form.password_field :password_confirmation, class: "form-control" %>
                    </div>

                    <div class="actions">
                      <%= form.submit %>
                    </div>
                  <% end %>
                <!-- <input type="text" class="form-control" placeholder="Email" required autofocus>
                <input type="password" class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember me
                </label>
                <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
                </form>
            </div>
            <a href="#" class="text-center new-account">Create an account </a> -->
          </div>
      </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Type of user</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='container'>
 <div class="row">

<%= render 'form', user: @user %>

<!--  <%= link_to 'Back', users_path %> -->
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>  <!-- What is this for? -->

<h4 class="uname">
  <strong>Welcome, <%= @user.first_name + ' ' + @user.last_name %></strong><br>
</h4>
<p id="type_user"><strong>Type of user: <%= @user.role %></strong></p>


<% if @user.role == "Lender" %>
  <button type="button" class="btn btn-primary btn-lg to-loan"><%= link_to "INVEST", '/loans#index' %></button>

<% if @a_count > 0 %>
    <div class="container">
      <h2>Active <span class="badge"><%= @a_count %></span></h2>

      <div class="table-responsive table-striped">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Guaranteed Tip</th>
            <th>Body</th>
            <th>Requester</th>
            <th>Status</th>
            <th colspan="2"></th>


            <!-- <th>City</th> -->
          </tr>
        </thead>
        <tbody>
          <% @lender_loans.each do |loan| %>
            <% if loan.lender_id == current_user.id && User.find(current_user.id).role == "Lender" && loan.status == "Active" %>
                      <tr>
                        <td><%= sprintf("$%.2f", (loan.amount_in_cents/100)) %></td>
                        <td><%= sprintf("$%.2f", (loan.tip_in_cents.to_f/100)) %></td>
                        <td><%= loan.body %></td>
                        <td><%= loan.user.first_name %></td>
                        <td><%= loan.status %></td>
                        <!-- <td>User.find(loan.user_id).first_name</td> -->
<!--                         <td><%= link_to 'Show', loan %></td>
 -->                        <td><%= link_to 'View', edit_loan_path(loan) %></td>
                      </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>

  <% if @c_count > 0 %>
    <div class="container">
      <h2>Active <span class="badge"><%= @c_count %></span></h2>

      <div class="table-responsive table-striped">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Guaranteed Tip</th>
            <th>Body</th>
            <th colspan="2"></th>


            <!-- <th>City</th> -->
          </tr>
        </thead>
        <tbody>
          <% @lender_loans.each do |loan| %>
            <% if loan.lender_id == current_user.id && User.find(current_user.id).role == "Lender" && loan.status == "Active" %>
                      <tr>
                        <td><%= sprintf("$%.2f", (loan.amount_in_cents/100)) %></td>
                        <td><%= sprintf("$%.2f", (loan.tip_in_cents.to_f/100)) %></td>
                        <td><%= loan.body %></td>
                        <td><%= loan.status %></td>
                        <!-- <td>User.find(loan.user_id).first_name</td> -->
<!--                         <td><%= link_to 'Show', loan %></td>
 -->                        <td><%= link_to 'View - fix link', edit_loan_path(loan) %></td>
                      </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>

<% end %>


<% if @user.role == "Borrower" %>
  <button type="button" class="btn btn-primary btn-lg to-loan" href="#"><%= link_to "NEW REQUEST", '/loans/new' %></button>
<% end %>
 </div>