config/routes.rb
Rails.application.routes.draw do
  root 'sessions#splashpage'
  # root 'sessions#new' #TODO work on this one!

  resources :sessions
  resources :users
  resources :loans

  # get '/cool' => 'rails#cool'
  # get '/sweet' => 'rails#sweet'
  #
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  #
  # post '/login' => 'sessions#create'
  # get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#create'
  get '/profilepage' => 'sessions#profilepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
	# belongs_to :lender, class_name: "User", foreign_key: "lender_id"
	# belongs_to :borrower, class_name: "User", foreign_key: "borrower_id"

  # validates :status, inclusion: { in: %w(pending filled repaid) }
  belongs_to :user
  # has_many :borrowers, class_name: "User", foreign_key: "lender_id"
 
  # belongs_to :lender, class_name: "User"

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy, :repay]
  after_action :http_request, only: :update

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
    # @user = User.find(params[:id])
    @all_loans = User.find(current_user.id).loans
    @p_count = 0 #count of pending loans
    @a_count = 0 #count of active loans
    @c_count = 0 #count of completed loans
    @loans.each do |pending|
      if pending.status == "Pending"
        @p_count = @p_count + 1
      end
    end

    @all_loans.each do |pending|
      if pending.status == "Active"
        @a_count = @a_count + 1
      end
    end

    @all_loans.each do |pending|
      if pending.status == "Completed"
        @c_count = @c_count + 1
      end
    end

  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    @invester = User.find(@loan.user.id)
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit

  end

  def repay

  end

  # POST /loans
  # POST /loans.json
  def create
    @user = User.find(current_user.id)
    @loan = @user.loans.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def http_request
      redirect_to :back, notice: "Payment Failed" and return unless @loan.save
      client = Dwolla.new
      borrower = User.find(@loan.user.id)
      invester = User.find(@loan.lender_id)

      if current_user.role == "Lender"

        # Get borrower href
        to = client.find_url(borrower.email)
        # Get lender source
        from = client.find_funding_source_url(invester.email)

        amount = "#{@loan.amount_in_cents/100}"

        client.send_money(from, to, amount)

      elsif current_user.role == "Borrower" && @loan.status == "Closed"

        # Get borrower href
        from = client.find_funding_source_url(borrower.email)
        # Get lender source
        to = client.find_url(invester.email)

        full_amount = @loan.tip_in_cents + @loan.amount_in_cents
        amount = "#{(full_amount.to_f/100)}"

        client.send_money(from, to, amount)

      end
      # client.send_money(from, to, amount)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:amount_in_cents, :body, :status, :lender_id, :tip_in_cents)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="wall">
                <img id="logo" src="https://trello-attachments.s3.amazonaws.com/5a00dc322b3c3a3c721a6912/5a00e674cdb313f96d9cdb2c/539b280fb58aee03ce2fe36c62fdae39/Logaster-13-vk-sharedImage-1000px.png"
                    alt="">
                  <%= form_with(model: loan, local: true, class: "all-form") do |form| %>
                    <% if loan.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

                        <ul>
                        <% loan.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="field">
                      <%= form.label :amount_in_cents, "Amount" %>
                      <%= form.select :amount_in_cents, options_for_select({"$5.00" => 500, "$10.00" => 1000, "$15.00" => 1500, "$20.00" => 2000, "$25.00" => 2500, "$30.00" => 3000}), class: 'form-control' %>
                    </div>

                    <div class="field">
                      <%= form.label :tip_in_cents, "Guaranteed Tip" %>
                      <%= form.select :tip_in_cents, options_for_select({"$0.00" => 000, "$1.50" => 150, "$3.00" => 300, "$4.50" => 450, "$6.00" => 600, "$7.50" => 750, "$9.00" => 900, "$10.50" => 1050}), class: 'form-control' %>
                    </div>

                    <div class="field">
                      <%= form.label :body, "Description" %>
                      <%= form.text_area :body, class: 'form-control' %>
                    </div>

                    <div class="actions" id="create_loan">
                      <%= form.submit %>
                    </div>
                  <% end %>
        </div>
      </div>
  </div>
</div>

app/views/loans/edit.html.erb
<h1>Current Loan</h1>

<ul id="current_loan">
	<li>Amount: <%= sprintf("$%.2f", (@loan.amount_in_cents/100)) %></li>
	<li>Guaranteed Tip: <%= sprintf("$%.2f", (@loan.tip_in_cents.to_f/100)) %></li>
	<li>Description: <%= @loan.body %></li>
	<li>Requester: <%= @loan.user.first_name %></li>
	<li>Status: <%= @loan.status %></li>
</ul>

<% if User.find(current_user.id).role == "Borrower" %>
	<%= render 'form', loan: @loan %>
<% end %>

<% if User.find(current_user.id).role == "Lender" %>
		<%= form_for @loan do |form| %>
	    <%= form.hidden_field(:lender_id, :value => current_user.id) %>
	    <%= form.hidden_field(:status, :value => "Active") %>

	    <%= form.submit "Invest" %>
		<% end %>
<% end %>

<%= link_to 'Show', @loan %> | <%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Amount in cents</th>
      <th>Body</th>
      <th>Status</th>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead> -->


  <% if @p_count > 0 && User.find(current_user.id).role == "Borrower" %>
    <div class="container">
      <h2 id="loan_index">Pending <span class="badge"><%= @p_count %></span></h2>

      <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Guaranteed Tip</th>
            <th>Description</th>
            <th colspan="2"></th>

            <!-- <th>City</th> -->
          </tr>
        </thead>
        <tbody>
          <% @loans.each do |loan| %>
            <% if loan.user_id == current_user.id && User.find(current_user.id).role == "Borrower" && loan.status == "Pending" %>
                      <tr>
                        <td><%= sprintf("$%.2f", (loan.amount_in_cents/100)) %></td>
                        <td><%= sprintf("$%.2f", (loan.tip_in_cents.to_f/100)) %></td>
                        <td><%= loan.body %></td>
                        <td><%= loan.status %></td>
                        <!-- <td>User.find(loan.user_id).first_name</td> -->
<!--                         <td><%= link_to 'Show', loan %></td>
 -->                        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
                        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>

  <% if @a_count > 0 %>
    <div class="container">
      <h2 id="loan_index">Active <span class="badge"><%= @a_count %></span></h2>

      <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Guaranteed Tip</th>
            <th>Description</th>
            <th colspan="2"></th>


            <!-- <th>City</th> -->
          </tr>
        </thead>
        <tbody>
          <% @loans.each do |loan| %>
            <% if loan.user_id == current_user.id && User.find(current_user.id).role == "Borrower" && loan.status == "Active" %>
                      <tr>
                        <td><%= sprintf("$%.2f", (loan.amount_in_cents/100)) %></td>
                        <td><%= sprintf("$%.2f", (loan.tip_in_cents.to_f/100)) %></td>
                        <td><%= loan.body %></td>
                        <td><%= loan.status %></td>
                        <!-- <td>User.find(loan.user_id).first_name</td> -->
<!--                         <td><%= link_to 'Show', loan %></td>
-->                        <td><%= link_to 'Pay', repay_loans_path(loan) %></td>
                      </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>

<!--
  <tbody>
    <% @loans.each do |loan| %>
      <% if loan.user_id == current_user.id && User.find(current_user.id).role == "Borrower" %>
        <tr>
          <td><%= loan.amount_in_cents %></td>
          <td><%= loan.body %></td>
          <td><%= loan.status %></td>
          <td><%= User.find(loan.user_id).first_name %></td>
          <td><%= link_to 'Show', loan %></td>
          <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
          <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
          <% nil %>
      <% end %>
      <% if User.find(current_user.id).role == "Lender" && loan.lender_id == nil %>
      <tr>
          <td><%= loan.amount_in_cents %></td>
          <td><%= loan.body %></td>
          <td><%= loan.status %></td>
          <td><%= User.find(loan.user_id).first_name %></td>
          <td><%= link_to 'Show', loan %></td>
          </tr>
      <% else %>
          <% nil %>
      <% end %>
    <% end %>
  </tbody>
</table> -->

<% if @p_count > 0 && User.find(current_user.id).role == "Lender" %>
    <div class="container">
      <h2 id="loan_index">Pending <span class="badge"><%= @p_count %></span></h2>

      <div class="table-responsive table-striped">
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Guaranteed Tip</th>
            <th>Description</th>
            <th>Requester</th>
            <th>Status</th>
            <th colspan="2"></th>

            <!-- <th>City</th> -->
          </tr>
        </thead>
        <tbody>
          <% @loans.each do |loan| %>
            <% if User.find(current_user.id).role == "Lender" && loan.status == "Pending" %>
                <tr>
                  <td><%= sprintf("$%.2f", (loan.amount_in_cents/100)) %></td>
                  <td><%= sprintf("$%.2f", (loan.tip_in_cents.to_f/100)) %></td>
                  <td><%= loan.body %></td>
                  <td><%= loan.user.first_name %></td>
                  <td><%= loan.status %></td>
                  <!-- <td>User.find(loan.user_id).first_name</td> -->
                          <td><%= link_to 'Show', loan %></td>
                         <!--  <td><%= link_to 'Edit', edit_loan_path(loan) %></td> -->
                  <!-- <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  <% end %>


<br>

<% if current_user.role == "Borrower" %>
  <p id="link_to" /><%= link_to 'New Loan', new_loan_path %></p>
<% end %>

app/views/loans/new.html.erb
<% if User.find(current_user.id).role == "Lender" %>
	<h1>Sorry you can't request loans with this account</h1>
<% else %>
	<%= render 'form', loan: @loan %>
<% end %>

<p class="back"><%= link_to 'Back', loans_path %></p>

app/views/loans/repay.html.erb
<h1>Repayment</h1>

<% tip = sprintf("$%.2f", (@loan.tip_in_cents.to_f/100)) %>
<% og_loan = sprintf("$%.2f", (@loan.amount_in_cents/100)) %>

<% full_amount = @loan.tip_in_cents + @loan.amount_in_cents %>

<% total = sprintf("$%.2f", (full_amount.to_f/100)) %>

<p>
  Loan Amount: <%= og_loan %>
</p>

<p>
  Guaranteed Tip: <%= tip %>
</p>

<%= form_for @loan do |form| %>

    <%= form.label :tip_in_cents, "Add to Tip?" %>
    <%= form.select :tip_in_cents, options_for_select({"$0.00" => 000+@loan.tip_in_cents, "$1.50" => 150+@loan.tip_in_cents, "$3.00" => 300+@loan.tip_in_cents, "$4.50" => 450+@loan.tip_in_cents}), class: 'form-control' %>
    <%= form.submit "Add To Tip" %>
<% end %>

<p>
  Total: <%= total %>
</p>

<% if User.find(current_user.id).role == "Borrower" %>
	<%= form_for @loan do |form| %>

	    <%= form.hidden_field(:status, :value => "Closed") %>

	    <%= form.submit "Repay" %>
	<% end %>
<% end %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>
<%= @invester.email %>
<p>
  <strong>Amount:</strong>
  <%= sprintf("$%.2f", (@loan.amount_in_cents/100)) %>
</p>

<p>
  <strong>Guaranteed Tip:</strong>
  <%= sprintf("$%.2f", (@loan.tip_in_cents.to_f/100)) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @loan.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @loan.status %>
</p>

<% if User.find(current_user.id).role == "Borrower" %>
  <% if @loan.status == "Pending" %>
	 <%= link_to 'Edit', edit_loan_path(@loan) %> |
	 <%= link_to 'Back', loans_path %>
  <% else %>
    <%= link_to 'Repay', repay_loans_path(@loan) %> |
    <%= link_to 'Back', loans_path %>
  <% end %>
<% end %>

<% if User.find(current_user.id).role == "Lender" %>
  <% if @loan.status == "Pending" %>
    <%= link_to 'Invest', edit_loan_path(@loan) %> |
    <%= link_to 'Back', loans_path %>
  <% else %>
    <%= link_to 'Back', loans_path %>
  <% end %>

<% end %>